# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20181003_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
