# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-05 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20181005_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='products_in_cart', to='ecommerce.Product'),
        ),
    ]
