# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20181008_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
